context:
  listener:
    classes: uk.ac.ebi.biostd.exporter.configuration.QueryLoader
server:
  port: 8181
management:
  endpoints:
    web:
      exposure:
        include:
          - scheduledtasks
          - health
          - info
spring:
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
        cacheServerConfiguration: true
        useLocalSessionState: true
        maintainTimeStats: false
      jdbc-url: # to be set in deployment script
      username: # to be set in deployment script
      password:

---
spring:
  profiles: local

jobs:
  backend-url: http://localhost:8586/biostd
  stats:
    enabled: false
    basePath: # ${SUBMISSIONS_PATH}/submission
    outFilePath: # ${OUTPUT_PATH}/stats.csv
    workers: 4
    cron: 0/10 * * * * ? # each 10 seconds
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds

  partial:
    enabled: false
    filePath: ./generated/
    fileName: studies_partial
    notificationUrl: http://localhost:8586/api/update/partial/
    deleteNotificationUrl: http://localhost:8586/api/delete/
    cron: 0/20 * * * * ? # each 20 seconds

  full:
    enabled: false
    allSubmissions:
      filePath: ./generated/
      fileName: studies
    publicOnlySubmissions:
      filePath: ./generated/
      fileName: studies
    workers: 1
    notificationUrl: http://localhost:8586/api/update/full
    query-modified: limit 100
    cron: 0 0/1 * * * ? # each minute

  pmc:
    export:
      enabled: false
      workers: 1
      user: elinks
      password: # to be set in deployment script
      ftpServer: labslink.ebi.ac.uk
      outputFolder: zs11dw62/testdir/aaa
      fileNameFormat: EPMCLinks.part%03d.xml
      ftpPort: 21
      cron: 0 0/1 * * * ? # each minute

---
spring:
  profiles: dev
jobs:
  backend-url: http://biostudy-bia.ebi.ac.uk:8586/biostd
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds
  partial:
    enabled: true
    filePath: /ebi/teams/biostudies/backend/development/updates/
    fileName: studies_partial
    notificationUrl: http://ribs:8080/biostudies/api/v1/index/reload/
    deleteNotificationUrl: http://ribs:8080/biostudies/api/v1/index/delete/
    cron: 0 0/5 5-19 * * ? # each five minutes between 5 am and 7 pm.
  full:
    enabled: true
    allSubmissions:
      filePath: /ebi/teams/biostudies/backend/development/updates/
      fileName: studies
    publicOnlySubmissions:
      filePath: /ebi/teams/biostudies/backend/development/updates/
      fileName: publicOnlyStudies
    workers: 4
    queryModified:
    notificationUrl: http://ribs:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 19 * * ? # everyday at 7 p.m.
    recordsThreshold: 1000000
  pmc:
    import:
      user: admin_user@ebi.ac.uk
      importPath: /nfs/ma/home/biostudy/EPMC-export/dump-2018-01
      submitterUserPath: /ebi/teams/biostudies/backend/development/usergroup/Users/a/admin_user@ebi.ac.uk
  ftp:
    baseFtpPath: /ebi/teams/biostudies/backend/development/ftp
    baseBioStudiesPath: /ebi/teams/biostudies/backend/development/submission
  users:
    baseDropboxPath: /ebi/teams/biostudies/backend/development/dropbox
    symLinksPath: /ebi/teams/biostudies/backend/development/usergroup/Users
  releaser:
    enabled: false

---
spring:
  profiles: beta
jobs:
  backend-url: http://biostudy-dev.ebi.ac.uk:10180/biostd-beta
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds
  stats:
    basePath: /nfs/biostudies/.adm/databases/beta/submission
    outFilePath: /nfs/biostudies/.adm/databases/beta/updates/stats.csv
    workers: 4
  partial:
    enabled: true
    filePath: /nfs/biostudies/.adm/databases/beta/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6b:8080/biostudies/api/v1/index/reload/
    deleteNotificationUrl: http://ves-ebi-6b:8080/biostudies/api/v1/index/delete/
    cron: 0 0/5 5-19 * * ? # each five minutes between 5 am and 7 pm.
  full:
    enabled: true
    allSubmissions:
      filePath: /nfs/biostudies/.adm/databases/beta/updates/
      fileName: studies
    publicOnlySubmissions:
      filePath: /nfs/biostudies/.adm/databases/beta/updates/
      fileName: publicOnlyStudies
    workers: 4
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 19 * * ? # everyday at 7 p.m.
    recordsThreshold: 1000000
  ftp:
    baseFtpPath: /nfs/biostudies/.adm/databases/beta/ftp
    baseBioStudiesPath: /nfs/biostudies/.adm/databases/beta/submission
  users:
    baseDropboxPath: /nfs/biostudies/ftp/pub/.dropbox
    symLinksPath: /nfs/biostudies/.adm/databases/beta/usergroup/Users
  releaser:
    enabled: false

---
spring:
  profiles: prod
jobs:
  backend-url: http://biostudy-prod.ebi.ac.uk:10080/biostd-prod
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds
  stats:
    enabled: true
    basePath: /nfs/biostudies/.adm/databases/prod/submission
    outFilePath: /nfs/biostudies/.adm/databases/prod/updates/stats.csv
    workers: 4
    cron: 0 0 22 4 * * # the fourth of each month at 10 p.m.
  partial:
    enabled: true
    filePath: /nfs/biostudies/.adm/databases/prod/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6e:8080/biostudies/preview/api/v1/index/reload/
    cron: 0 0/5 5-19 * * ? # each five minutes between 5 am and 7 pm.
  full:
    enabled: true
    allSubmissions:
      filePath: /nfs/biostudies/.adm/databases/prod/updates/
      fileName: studies
    publicOnlySubmissions:
      filePath: /nfs/biostudies/prod/external
      fileName: publicOnlyStudies
    workers: 4
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    deleteNotificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/delete/
    cron: 0 0 22 * * ? # everyday at 10 p.m.
    recordsThreshold: 1000000
  pmc:
    export:
      enabled: true
      workers: 4
      user: elinks
      password: # to set in execution script
      ftpServer: labslink.ebi.ac.uk
      outputFolder: zs11dw62/links
      fileNameFormat: EPMCLinks.part%03d.xml
      ftpPort: 21
      cron: 0 0 08 * * ? # everyday at 08 a.m.
    import:
      user: manager
  users:
    baseDropboxPath: /nfs/biostudies/ftp/pub/.dropbox
    symLinksPath: /nfs/biostudies/.adm/databases/prod/usergroup/Users
  releaser:
    enabled: false
