context:
  listener:
    classes: uk.ac.ebi.biostd.exporter.configuration.QueryLoader
server:
  port: 8181
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false
spring:
  boot:
    admin:
      client:
        url: http://biostudy-prod.ebi.ac.uk:8590
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 30
      connection-test-query: SELECT 1 FROM DUAL
      jdbc-url: # to be set in deployment script
      username: # to be set in deployment script
      password:

---
spring:
  profiles: local

jobs:
  backend-url: http://localhost:8586/biostd
  stats:
    enabled: false
    imagingProjects:
      - BioImages
    basePath: # ${SUBMISSIONS_PATH}/submission
    outFilePath: # ${OUTPUT_PATH}/stats.csv
    workers: 4
    cron: 0/10 * * * * ? # each 10 seconds
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds

  partial:
    enabled: false
    filePath: ./generated/
    fileName: studies_partial
    notificationUrl: http://localhost:8586/api/update/partial/
    deleteNotificationUrl: http://localhost:8586/api/delete/
    cron: 0/20 * * * * ? # each 20 seconds

  full:
    enabled: false
    allSubmissions:
      filePath: ./generated/
      fileName: studies
    publicOnlySubmissions:
      filePath: ./generated/
      fileName: studies
    workers: 1
    notificationUrl: http://localhost:8586/api/update/full
    query-modified: limit 100
    cron: 0 0/1 * * * ? # each minute

  pmc:
    export:
      enabled: false
      workers: 1
      user: elinks
      password: # to be set in deployment script
      ftpServer: labslink.ebi.ac.uk
      outputFolder: zs11dw62/testdir/aaa
      fileNameFormat: EPMCLinks.part%03d.xml
      ftpPort: 21
      cron: 0 0/1 * * * ? # each minute

---
spring:
  profiles: dev
jobs:
  backend-url: http://biostudy-bia.ebi.ac.uk:8586/biostd
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds
  stats:
    enabled: false
    imagingProjects:
      - BioImages
    basePath: /ebi/teams/biostudies/backend/development/submission
    outFilePath: /ebi/teams/biostudies/backend/development/updates/stats.csv
    workers: 4
  partial:
    enabled: true
    filePath: /ebi/teams/biostudies/backend/development/updates/
    fileName: studies_partial
    notificationUrl: http://ribs:8080/biostudies/api/v1/index/reload/
    deleteNotificationUrl: http://ribs:8080/biostudies/api/v1/index/delete/
    cron: 0 0/5 5-19 * * ? # Every 5 minutes, between 05:00 AM and 07:59 PM.
  full:
    enabled: true
    allSubmissions:
      filePath: /ebi/teams/biostudies/backend/development/updates/
      fileName: studies
    publicOnlySubmissions:
      filePath: /ebi/teams/biostudies/backend/development/updates/
      fileName: publicOnlyStudies
    workers: 4
    queryModified:
    notificationUrl: http://ribs:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 19 * * ? # everyday at 7 p.m.
    recordsThreshold: 1
  ftp:
    baseFtpPath: /ebi/teams/biostudies/backend/development/ftp
    baseBioStudiesPath: /ebi/teams/biostudies/backend/development/submission
  users:
    baseDropboxPath: /ebi/teams/biostudies/backend/development/dropbox
    symLinksPath: /ebi/teams/biostudies/backend/development/usergroup/Users
  releaser:
    enabled: false
  pmc:
    export:
      enabled: false
      workers: 1
      user: elinks
      password: # to be set in deployment script
      ftpServer: labslink.ebi.ac.uk
      outputFolder: zs11dw62/testdir/aaa
      fileNameFormat: EPMCLinks.part%03d.xml
      ftpPort: 21
      cron: 0 0/1 * * * ? # each minute

---
spring:
  profiles: beta
jobs:
  backend-url: http://biostudy-dev.ebi.ac.uk:10180/biostd-beta
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds
  stats:
    enabled: true
    imagingProjects:
      - BioImages
      - JCB
    basePath: /nfs/biostudies/.adm/databases/beta/submission
    outFilePath: /nfs/biostudies/.adm/databases/beta/updates/stats.csv
    workers: 2
    cron: 0 0 22 4 * * # the fourth of each month at 10 p.m.
  partial:
    enabled: true
    filePath: /nfs/biostudies/.adm/databases/beta/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6b:8080/biostudies/api/v1/index/reload/
    deleteNotificationUrl: http://ves-ebi-6b:8080/biostudies/api/v1/index/delete/
    cron: 0 0/5 5-19 * * ? # each five minutes between 5 am and 7 pm.
  full:
    enabled: true
    allSubmissions:
      filePath: /nfs/biostudies/.adm/databases/beta/updates/
      fileName: studies
    publicOnlySubmissions:
      filePath: /nfs/biostudies/.adm/databases/beta/updates/
      fileName: publicOnlyStudies
    workers: 2
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 19 * * ? # everyday at 7 p.m.
    recordsThreshold: 500000
  ftp:
    baseFtpPath: /nfs/biostudies/.adm/databases/beta/ftp
    baseBioStudiesPath: /nfs/biostudies/.adm/databases/beta/submission
  users:
    baseDropboxPath: /nfs/biostudies/ftp/pub/.dropbox
    symLinksPath: /nfs/biostudies/.adm/databases/beta/usergroup/Users
  releaser:
    enabled: true
    cron: 0 0 18 * * ? # everyday at 6 p.m.

---
spring:
  profiles: prod
jobs:
  backend-url: http://biostudy-prod.ebi.ac.uk:10080/biostd-prod
  dummy:
    enabled: false
    cron: 0/10 * * * * ? # each 10 seconds
  stats:
    enabled: true
    imagingProjects:
      - BioImages
      - JCB
    basePath: /nfs/biostudies/.adm/databases/prod/submission
    outFilePath: /nfs/biostudies/.adm/databases/prod/updates/stats.csv
    workers: 4
    cron: 0 0 22 4 * * # the fourth of each month at 10 p.m.
  partial:
    enabled: true
    filePath: /nfs/biostudies/.adm/databases/prod/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6e:8080/biostudies/preview/api/v1/index/reload/
    cron: 0 0/5 5-19 * * ? # each five minutes between 5 am and 7 pm.
  full:
    enabled: true
    allSubmissions:
      filePath: /nfs/biostudies/.adm/databases/prod/updates/encoding/
      fileName: studies
    publicOnlySubmissions:
      filePath: /nfs/biostudies/.adm/databases/prod/updates/encoding/
      fileName: publicOnlyStudies
    workers: 4
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    deleteNotificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/delete/
    cron: 0 0 22 * * ? # everyday at 10 p.m.
    recordsThreshold: 500000
  pmc:
    export:
      enabled: true
      workers: 4
      user: elinks
      password: # to set in execution script
      ftpServer: labslink.ebi.ac.uk
      outputFolder: zs11dw62/links
      fileNameFormat: EPMCLinks.part%03d.xml
      ftpPort: 21
      cron: 0 0 08 * * ? # everyday at 08 a.m.
  users:
    baseDropboxPath: /nfs/biostudies/ftp/pub/.dropbox
    symLinksPath: /nfs/biostudies/.adm/databases/prod/usergroup/Users
  releaser:
    enabled: true
    cron: 0 0 21 * * ? # everyday at 9 p.m.
  ftp:
    baseFtpPath: /nfs/biostudies/ftp/pub
    baseBioStudiesPath: /nfs/biostudies/.adm/databases/prod/submission
