server:
  port: 8181
logging:
  file: logs/log.file
  level: INFO
spring:
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
        cacheServerConfiguration: true
        useLocalSessionState: true
        maintainTimeStats: false
      jdbcUrl: # to set in deployment script
      username: # to set in deployment script
      password: # to set in deployment script

---

spring:
  profiles: local
jobs:
  partial:
    filePath: ./generated/
    fileName: studies_partial
    notificationUrl: http://localhost:8181/api/update/partial/
    cron: 0/20 * * * * ? # Each 20 seconds
  full:
    filePath: ./generated/
    fileName: studies
    workers: 4
    notificationUrl: http://localhost:8181/api/update/full
    cron: 0 0/1 * * * ? # Each minute

---

spring:
  profiles: beta
jobs:
  partial:
    filePath: /nfs/biostudies/.adm/databases/beta/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/
    cron: 0 0/5 5-19 * * ? # Each five minute between 5 am and 7 pm.

  full:
    filePath: /nfs/biostudies/.adm/databases/beta/updates/
    fileName: studies
    workers: 4
    queryModified: and id = 1793573
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 19 * * ? # Everyday at 7 p.m.

---

spring:
  profiles: prod
jobs:
  partial:
    filePath: /nfs/biostudies/.adm/databases/prod/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/
    cron: 0 0 0 25 12 ? # at Christmas TODO: add support to "enable" flag instead

  full:
    filePath: /nfs/biostudies/.adm/databases/prod/updates/
    fileName: studies
    workers: 4
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 22 * * ? # Everyday at 10 p.m.
