server:
  port: 8181
logging:
  file: logs/log.file
  level: INFO
spring:
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      jdbcUrl:
      username:
      password:
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
        cacheServerConfiguration: true
        useLocalSessionState: true
        maintainTimeStats: false

---

spring:
  profiles: local
jobs:
  partial:
    filePath: ./generated/
    fileName: studies_partial.json
    notificationUrl: http://localhost:8181/api/update/partial
    cron: 0/20 * * * * ? # Each 20 seconds
  full:
    filePath: ./generated/
    fileName: studies.json
    workers: 20
    queryModified: limit 10000
    notificationUrl: http://localhost:8181/api/update/full
    cron: 0 0/1 * * * ? # Each minute

---

spring:
  profiles: beta
jobs:
  partial:
    filePath: /nfs/biostudies/.adm/databases/beta/ui-exports/
    fileName: studies_partial.json
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/${jobs.partial.fileName}
    cron: 0 0/5 7-22 * * ? # Each five minute between 7 am and 10 pm.

  full:
    filePath: /nfs/biostudies/.adm/databases/beta/ui-exports/
    fileName: studies.json
    workers: 20
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 23 * * ? # Everyday at 11 p.m.
