context:
  listener:
    classes: uk.ac.ebi.biostd.exporter.configuration.QueryLoader
server:
  port: 8181
logging:
  file: logs/log.file
  level: INFO
spring:
  profiles:
    active: local
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
        cacheServerConfiguration: true
        useLocalSessionState: true
        maintainTimeStats: false
      jdbc-url: # to be set in deployment script
      username: # to be set in deployment script
      password: # to be set in deployment script

---

spring:
  profiles: local
jobs:
  partial:
    filePath: ./generated/
    fileName: studies_partial
    notificationUrl: http://localhost:8181/api/update/partial/
    cron: 0/20 * * * * ? # each 20 seconds
  full:
    filePath: ./generated/
    fileName: studies
    workers: 4
    notificationUrl: http://localhost:8181/api/update/full
    cron: 0 0/1 * * * ? # each minute
    query-modified: and id = 1793573

---

spring:
  profiles: beta
jobs:
  partial:
    filePath: /nfs/biostudies/.adm/databases/beta/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/
    cron: 0 0/5 5-19 * * ? # each five minute between 5 am and 7 pm.

  full:
    filePath: /nfs/biostudies/.adm/databases/beta/updates/
    fileName: studies
    workers: 4
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 19 * * ? # everyday at 7 p.m.

---

spring:
  profiles: prod
jobs:
  partial:
    filePath: /nfs/biostudies/.adm/databases/prod/updates/
    fileName: studies_partial
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/
    cron: 0 0 0 25 12 ? # at Christmas TODO: add support to "enable" flag instead

  full:
    filePath: /nfs/biostudies/.adm/databases/prod/updates/
    fileName: studies
    workers: 4
    queryModified:
    notificationUrl: http://ves-ebi-6f:8080/biostudies/api/v1/index/reload/default
    cron: 0 0 22 * * ? # everyday at 10 p.m.

  pmd:
    export:
      workers: 4
      user: elinks
      password: 8VhrURVH
      ftpServer: labslink.ebi.ac.uk
      outputFolder: zs11dw62/testdir/aaa/
      cron: 0 0 07 * * ? # everyday at 7 a.m.
