# Server properties are used only for local deployment and jar mode, they are ignored in "war mode"
server:
  port: 8586
  contextPath: /biostd

biostudy:
  baseDir: # set your nfs location i.e /home/jcamilorada/Projects/BioStudies/NFS
  tokenHash: biostd

spring:
  mail:
    host: localhost
  thymeleaf:
    prefix: classpath:/email/
    suffix: .html
    mode: LEGACYHTML5
    enabled: false


