# Only use for local deployment and jar mode, it is excluded from war
server:
  port: 8586
  contextPath: /biostd

biostd:
  baseDir: /home/jcamilorada/Projects/BioStudies/NFS
  configFile: /home/jcamilorada/Projects/BioStudies/NFS/config.properties
spring:
  datasource:
    tomcat:
      init-s-q-l: select 1
