# Server properties are used only for local deployment and jar mode, they are ignored in "war mode"
server:
  port: 8586
  contextPath: /biostd

biostudy:
  baseDir: # set your nfs location i.e /home/jcamilorada/Projects/BioStudies/NFS
  configFile: # set config file location i.e /home/jcamilorada/Projects/BioStudies/NFS/config.properties
  tokenHash: biostd

spring:
  mail:
    host: localhost
  thymeleaf:
    prefix: classpath:/email/
    suffix: .html
    mode: LEGACYHTML5

eutoxrisk-file-validator:
  enabled: true
  project-id: EU-ToxRisk
  endpoint: https://eutoxrisk-validator.cloud.douglasconnect.com/v1/validate
  thread-pool:
    core-pool-size: 1
    max-pool-size: 2
