# Only use for local deployment and jar mode, it is excluded from war
server:
  port: 8586
  contextPath: /biostd

biostudy:
  baseDir: /home/jcamilorada/Projects/BioStudies/NFS
  configFile: /home/jcamilorada/Projects/BioStudies/NFS/config.properties
