# Server properties are used only for local deployment and jar mode, they are ignored in "war mode"
server:
  port: 8586
  servlet:
    contextPath: /biostd

biostd:
  baseDir: # main file system location, config.properties file is expected to be at root level.

biostudy:
  tokenHash: biostd
  environment: DEV

spring:
  mail:
    host: localhost
  thymeleaf:
    prefix: classpath:/email/
    suffix: .html
    mode: LEGACYHTML5
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

eutoxrisk-file-validator:
  enabled: false
  project-id: EU-ToxRisk
  endpoint: https://eutoxrisk-validator.cloud.douglasconnect.com/v1/validate
