image: gradle:5.4.1-jdk8
include:
  - local: '/ci/webapp.yml'
  - local: '/ci/exporter.yml'

stages:
  - build-test
  - deploy-dev-ftp
  - deploy-beta-ftp
  - deploy-dev-webapp
  - deploy-beta-webapp
  - deploy-prod-webapp
  - deploy-dev-exporter
  - deploy-beta-exporter
  - deploy-prod-exporter

build-job:
  stage: build-test
  script: gradle clean build bootJar
  artifacts:
    paths:
      - BackendWebApp/build/libs/biostudy.jar
      - Exporter/build/libs/Exporter-0.0.1-SNAPSHOT.jar
      - FtpServer/build/libs/FtpServer-0.0.1-SNAPSHOT.jar
