image: gradle:6.5.1-jdk8
include:
  - local: '/ci/exporter.yml'

stages:
  - build-test
  - deploy-dev-exporter
  - deploy-beta-exporter
  - deploy-prod-exporter

build-job:
  stage: build-test
  script: gradle clean :Exporter:build :Exporter:bootJar
  artifacts:
    paths:
      - Exporter/build/libs/Exporter-0.0.1-SNAPSHOT.jar
